import type { EnemyArchetype, EnemyType } from '@/game/types/GameTypes';

export const ENEMY_ARCHETYPES: Record<EnemyType, EnemyArchetype> = {
  'pulse-drone': {
    type: 'pulse-drone',
    label: 'Pulse Drone',
    maxHp: 1,
    scoreValue: 140,
    radius: 22,
    speed: 240,
    lockSlots: 1,
    threat: 1,
  },
  'shield-node': {
    type: 'shield-node',
    label: 'Shield Node',
    maxHp: 2,
    scoreValue: 260,
    radius: 28,
    speed: 196,
    lockSlots: 2,
    threat: 2,
  },
  'chain-cluster': {
    type: 'chain-cluster',
    label: 'Chain Cluster',
    maxHp: 1,
    scoreValue: 120,
    radius: 18,
    speed: 252,
    lockSlots: 1,
    threat: 1,
  },
  'sniper-sigil': {
    type: 'sniper-sigil',
    label: 'Sniper Sigil',
    maxHp: 2,
    scoreValue: 320,
    radius: 26,
    speed: 188,
    lockSlots: 2,
    threat: 3,
    chargeDuration: 4.5,
  },
  'distortion-mine': {
    type: 'distortion-mine',
    label: 'Distortion Mine',
    maxHp: 2,
    scoreValue: 280,
    radius: 24,
    speed: 168,
    lockSlots: 2,
    threat: 3,
    chargeDuration: 2.6,
  },
};
